"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogClose,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { VisuallyHidden } from "radix-ui";
import { User, MapPin, Users, Mail, RotateCcw } from "lucide-react";
import type { Recipient } from "@/types/recipient";
import {
  AddressAutocomplete,
  type AddressData,
  type AddressValidationStatus,
} from "@/components/address-autocomplete";
import { useSession } from "@/context/session-context";
import { generateAddressTo } from "@/utils/address-to";

const TITLE_OPTIONS = [
  { value: "", label: "None" },
  { value: "Mr.", label: "Mr." },
  { value: "Mrs.", label: "Mrs." },
  { value: "Ms.", label: "Ms." },
  { value: "Miss", label: "Miss" },
  { value: "Dr.", label: "Dr." },
  { value: "Prof.", label: "Prof." },
  { value: "Rev.", label: "Rev." },
  { value: "Hon.", label: "Hon." },
];

interface RecipientEditDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  recipient: Recipient;
  onSave: (updates: Partial<Recipient>) => void;
}

interface RecipientEditDialogContentProps {
  recipient: Recipient;
  onSave: (updates: Partial<Recipient>) => void;
  onClose: () => void;
}

function RecipientEditDialogContent({
  recipient,
  onSave,
  onClose,
}: RecipientEditDialogContentProps) {
  const { googleMapsApiKey } = useSession();
  const [formData, setFormData] = useState({
    title: recipient.title || "",
    firstName: recipient.firstName || "",
    lastName: recipient.lastName || "",
    partnerTitle: recipient.partnerTitle || "",
    partnerFirst: recipient.partnerFirst || "",
    partnerLast: recipient.partnerLast || "",
    addressTo: recipient.addressTo || "",
    addressToOverridden: recipient.addressToOverridden || false,
    address1: recipient.address1 || "",
    address2: recipient.address2 || "",
    city: recipient.city || "",
    state: recipient.state || "",
    zip: recipient.zip || "",
    country: recipient.country || "",
  });

  // Track validation status changes from address autocomplete
  const [validationStatus, setValidationStatus] =
    useState<AddressValidationStatus | null>(null);

  // Recalculate addressTo when name fields change (if not overridden)
  const recalculateAddressTo = (data: typeof formData) => {
    if (data.addressToOverridden) return data.addressTo;
    return generateAddressTo({
      title: data.title,
      firstName: data.firstName,
      lastName: data.lastName,
      partnerTitle: data.partnerTitle,
      partnerFirst: data.partnerFirst,
      partnerLast: data.partnerLast,
    });
  };

  // Fields that trigger addressTo recalculation
  const nameFields = [
    "title",
    "firstName",
    "lastName",
    "partnerTitle",
    "partnerFirst",
    "partnerLast",
  ];

  const handleChange =
    (field: keyof typeof formData) =>
    (e: React.ChangeEvent<HTMLInputElement>) => {
      setFormData((prev) => {
        const updated = { ...prev, [field]: e.target.value };
        // Recalculate addressTo if a name field changed and not overridden
        if (nameFields.includes(field)) {
          updated.addressTo = recalculateAddressTo(updated);
        }
        return updated;
      });
    };

  const handleTitleChange = (
    field: "title" | "partnerTitle",
    value: string,
  ) => {
    setFormData((prev) => {
      const updated = { ...prev, [field]: value === "none" ? "" : value };
      // Recalculate addressTo when title changes
      updated.addressTo = recalculateAddressTo(updated);
      return updated;
    });
  };

  const handleAddressToChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = e.target.value;
    setFormData((prev) => ({
      ...prev,
      addressTo: newValue,
      addressToOverridden: true, // Mark as overridden when user manually edits
    }));
  };

  const handleResetAddressTo = () => {
    setFormData((prev) => {
      const autoGenerated = generateAddressTo({
        title: prev.title,
        firstName: prev.firstName,
        lastName: prev.lastName,
        partnerTitle: prev.partnerTitle,
        partnerFirst: prev.partnerFirst,
        partnerLast: prev.partnerLast,
      });
      return {
        ...prev,
        addressTo: autoGenerated,
        addressToOverridden: false,
      };
    });
  };

  const handleAddressChange = (address: AddressData) => {
    setFormData((prev) => ({
      ...prev,
      address1: address.address1,
      address2: address.address2,
      city: address.city,
      state: address.state,
      zip: address.zip,
      country: address.country,
    }));
  };

  const currentAddress: AddressData = {
    address1: formData.address1,
    address2: formData.address2,
    city: formData.city,
    state: formData.state,
    zip: formData.zip,
    country: formData.country,
  };

  const handleSave = () => {
    const updates: Partial<Recipient> = {
      ...formData,
      lastModified: new Date().toISOString(),
    };

    // Include validation status if it was updated via autocomplete
    if (validationStatus) {
      updates.addressValidated = validationStatus.isVerified;
      updates.formattedAddress = validationStatus.formattedAddress;
      updates.addressValidationError = validationStatus.validationError;
    }

    onSave(updates);
    onClose();
  };

  const hasChanges =
    Object.keys(formData).some((key) => {
      const formValue = formData[key as keyof typeof formData];
      const recipientValue = recipient[key as keyof Recipient];
      // Handle boolean comparison for addressToOverridden
      if (key === "addressToOverridden") {
        return formValue !== (recipientValue ?? false);
      }
      return formValue !== (recipientValue || "");
    }) || validationStatus !== null;

  return (
    <>
      {/* Accessible title and description (visually hidden) */}
      <VisuallyHidden.Root>
        <DialogTitle>Edit Recipient</DialogTitle>
        <DialogDescription>
          Edit the recipient's name and address information
        </DialogDescription>
      </VisuallyHidden.Root>

      {/* Header */}
      <div className="flex flex-col gap-4 border-b border-gray-100 px-8 pt-8 pb-6">
        <div className="flex items-center gap-4">
          {/* Icon */}
          <div
            className="flex size-14 shrink-0 items-center justify-center rounded-2xl"
            style={{
              background: "var(--gradient-primary)",
              boxShadow: "var(--shadow-card)",
            }}
          >
            <User className="size-6 text-white" />
          </div>
          {/* Title and description */}
          <div className="flex flex-col gap-1">
            <h2 className="text-3xl font-bold text-gray-900">Edit Recipient</h2>
            <p className="text-sm text-gray-600">
              Update the recipient's name and address information
            </p>
          </div>
        </div>
      </div>

      {/* Body - min-h ensures space for address dropdown */}
      <div className="flex min-h-100 flex-col gap-6 px-8 py-6">
        {/* Primary Person Section */}
        <div className="flex flex-col gap-4">
          <div className="flex items-center gap-2">
            <User className="size-4 text-gray-500" />
            <span className="text-sm font-semibold text-gray-900">
              Primary Person
            </span>
          </div>
          <div className="grid grid-cols-6 gap-3">
            <div className="col-span-1">
              <label className="mb-1.5 block text-xs font-medium text-gray-700">
                Title
              </label>
              <Select
                value={formData.title || "none"}
                onValueChange={(value) => handleTitleChange("title", value)}
              >
                <SelectTrigger className="h-11! w-full rounded-xl border-2 border-gray-200 bg-white px-4 text-sm">
                  <SelectValue placeholder="Title" />
                </SelectTrigger>
                <SelectContent>
                  {TITLE_OPTIONS.map((option) => (
                    <SelectItem
                      key={option.value || "none"}
                      value={option.value || "none"}
                    >
                      {option.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="col-span-2">
              <label className="mb-1.5 block text-xs font-medium text-gray-700">
                First Name
              </label>
              <Input
                value={formData.firstName}
                onChange={handleChange("firstName")}
                placeholder="John"
                className="h-11 rounded-xl border-2 border-gray-200 bg-white px-4 text-sm"
              />
            </div>
            <div className="col-span-3">
              <label className="mb-1.5 block text-xs font-medium text-gray-700">
                Last Name
              </label>
              <Input
                value={formData.lastName}
                onChange={handleChange("lastName")}
                placeholder="Smith"
                className="h-11 rounded-xl border-2 border-gray-200 bg-white px-4 text-sm"
              />
            </div>
          </div>
        </div>

        {/* Partner Section */}
        <div className="flex flex-col gap-4">
          <div className="flex items-center gap-2">
            <Users className="size-4 text-gray-500" />
            <span className="text-sm font-semibold text-gray-900">
              Partner (Optional)
            </span>
          </div>
          <div className="grid grid-cols-6 gap-3">
            <div className="col-span-1">
              <label className="mb-1.5 block text-xs font-medium text-gray-700">
                Title
              </label>
              <Select
                value={formData.partnerTitle || "none"}
                onValueChange={(value) =>
                  handleTitleChange("partnerTitle", value)
                }
              >
                <SelectTrigger className="h-11! w-full rounded-xl border-2 border-gray-200 bg-white px-4 text-sm">
                  <SelectValue placeholder="Title" />
                </SelectTrigger>
                <SelectContent>
                  {TITLE_OPTIONS.map((option) => (
                    <SelectItem
                      key={option.value || "none"}
                      value={option.value || "none"}
                    >
                      {option.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="col-span-2">
              <label className="mb-1.5 block text-xs font-medium text-gray-700">
                First Name
              </label>
              <Input
                value={formData.partnerFirst}
                onChange={handleChange("partnerFirst")}
                placeholder="Jane"
                className="h-11 rounded-xl border-2 border-gray-200 bg-white px-4 text-sm"
              />
            </div>
            <div className="col-span-3">
              <label className="mb-1.5 block text-xs font-medium text-gray-700">
                Last Name
              </label>
              <Input
                value={formData.partnerLast}
                onChange={handleChange("partnerLast")}
                placeholder="Smith"
                className="h-11 rounded-xl border-2 border-gray-200 bg-white px-4 text-sm"
              />
            </div>
          </div>
        </div>

        {/* Address To Section */}
        <div className="flex flex-col gap-4">
          <div className="flex items-center gap-2">
            <Mail className="size-4 text-gray-500" />
            <span className="text-sm font-semibold text-gray-900">
              Address To
            </span>
            {formData.addressToOverridden && (
              <span className="rounded-full bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-700">
                Custom
              </span>
            )}
          </div>
          <div className="flex gap-2">
            <Input
              value={formData.addressTo}
              onChange={handleAddressToChange}
              placeholder="e.g., Mr. and Mrs. John Smith"
              className="h-11 flex-1 rounded-xl border-2 border-gray-200 bg-white px-4 text-sm"
            />
            {formData.addressToOverridden && (
              <Button
                type="button"
                variant="outline"
                onClick={handleResetAddressTo}
                className="h-11 shrink-0 gap-2 rounded-xl border-2 border-gray-200 px-4"
                title="Reset to auto-generated"
              >
                <RotateCcw className="size-4" />
                Reset
              </Button>
            )}
          </div>
          <p className="text-xs text-gray-500">
            This is the formal name line that appears on the envelope. It's
            automatically generated from the names above but can be customized.
          </p>
        </div>

        {/* Address Section */}
        <div className="flex flex-col gap-4">
          <div className="flex items-center gap-2">
            <MapPin className="size-4 text-gray-500" />
            <span className="text-sm font-semibold text-gray-900">Address</span>
          </div>

          {/* Address Autocomplete with verification status */}
          <AddressAutocomplete
            value={currentAddress}
            onChange={handleAddressChange}
            onValidationChange={setValidationStatus}
            isVerified={
              validationStatus?.isVerified ?? recipient.addressValidated
            }
            formattedAddress={
              validationStatus?.formattedAddress ?? recipient.formattedAddress
            }
            validationError={
              validationStatus?.validationError ??
              recipient.addressValidationError
            }
            googleMapsApiKey={googleMapsApiKey}
          />

          {/* Manual address fields (shown below autocomplete for fine-tuning) */}
          <details className="group">
            <summary className="cursor-pointer text-xs font-medium text-gray-500 hover:text-gray-700">
              Edit address details manually
            </summary>
            <div className="mt-3 flex flex-col gap-3">
              <div>
                <label className="mb-1.5 block text-xs font-medium text-gray-700">
                  Street Address
                </label>
                <Input
                  value={formData.address1}
                  onChange={handleChange("address1")}
                  placeholder="123 Main Street"
                  className="h-11 rounded-xl border-2 border-gray-200 bg-white px-4 text-sm"
                />
              </div>
              <div>
                <label className="mb-1.5 block text-xs font-medium text-gray-700">
                  Apt, Suite, Unit (Optional)
                </label>
                <Input
                  value={formData.address2}
                  onChange={handleChange("address2")}
                  placeholder="Apt 4B"
                  className="h-11 rounded-xl border-2 border-gray-200 bg-white px-4 text-sm"
                />
              </div>
              <div className="grid grid-cols-6 gap-3">
                <div className="col-span-2">
                  <label className="mb-1.5 block text-xs font-medium text-gray-700">
                    City
                  </label>
                  <Input
                    value={formData.city}
                    onChange={handleChange("city")}
                    placeholder="New York"
                    className="h-11 rounded-xl border-2 border-gray-200 bg-white px-4 text-sm"
                  />
                </div>
                <div className="col-span-2">
                  <label className="mb-1.5 block text-xs font-medium text-gray-700">
                    State
                  </label>
                  <Input
                    value={formData.state}
                    onChange={handleChange("state")}
                    placeholder="NY"
                    className="h-11 rounded-xl border-2 border-gray-200 bg-white px-4 text-sm"
                  />
                </div>
                <div className="col-span-2">
                  <label className="mb-1.5 block text-xs font-medium text-gray-700">
                    ZIP Code
                  </label>
                  <Input
                    value={formData.zip}
                    onChange={handleChange("zip")}
                    placeholder="10001"
                    className="h-11 rounded-xl border-2 border-gray-200 bg-white px-4 text-sm"
                  />
                </div>
              </div>
              <div>
                <label className="mb-1.5 block text-xs font-medium text-gray-700">
                  Country
                </label>
                <Input
                  value={formData.country}
                  onChange={handleChange("country")}
                  placeholder="United States"
                  className="h-11 rounded-xl border-2 border-gray-200 bg-white px-4 text-sm"
                />
              </div>
            </div>
          </details>
        </div>
      </div>

      {/* Footer */}
      <div className="flex items-center justify-between border-t border-gray-100 px-8 py-6">
        <DialogClose asChild>
          <Button
            variant="ghost"
            className="h-12 px-6 text-base font-semibold text-gray-700"
          >
            Cancel
          </Button>
        </DialogClose>
        <Button
          onClick={handleSave}
          disabled={!hasChanges}
          className="h-12 gap-2 rounded-xl px-8 text-base font-semibold text-white"
          style={{
            background: hasChanges
              ? "linear-gradient(90deg, #6366f1 0%, #8b5cf6 100%)"
              : undefined,
          }}
        >
          Save Changes
        </Button>
      </div>
    </>
  );
}

export function RecipientEditDialog({
  open,
  onOpenChange,
  recipient,
  onSave,
}: RecipientEditDialogProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent
        className="flex max-h-[90vh] w-2xl max-w-[calc(100%-2rem)] flex-col overflow-visible rounded-3xl p-0 sm:max-w-2xl"
        showCloseButton={false}
        aria-describedby={undefined}
      >
        {open && (
          <RecipientEditDialogContent
            recipient={recipient}
            onSave={onSave}
            onClose={() => onOpenChange(false)}
          />
        )}
      </DialogContent>
    </Dialog>
  );
}
