/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImportPreviewRouteImport } from './routes/import-preview'
import { Route as ImportRouteImport } from './routes/import'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as ConfigureRouteImport } from './routes/configure'
import { Route as IndexRouteImport } from './routes/index'

const ImportPreviewRoute = ImportPreviewRouteImport.update({
  id: '/import-preview',
  path: '/import-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRoute = ConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configure': typeof ConfigureRoute
  '/editor': typeof EditorRoute
  '/import': typeof ImportRoute
  '/import-preview': typeof ImportPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configure': typeof ConfigureRoute
  '/editor': typeof EditorRoute
  '/import': typeof ImportRoute
  '/import-preview': typeof ImportPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configure': typeof ConfigureRoute
  '/editor': typeof EditorRoute
  '/import': typeof ImportRoute
  '/import-preview': typeof ImportPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/configure' | '/editor' | '/import' | '/import-preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/configure' | '/editor' | '/import' | '/import-preview'
  id:
    | '__root__'
    | '/'
    | '/configure'
    | '/editor'
    | '/import'
    | '/import-preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigureRoute: typeof ConfigureRoute
  EditorRoute: typeof EditorRoute
  ImportRoute: typeof ImportRoute
  ImportPreviewRoute: typeof ImportPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/import-preview': {
      id: '/import-preview'
      path: '/import-preview'
      fullPath: '/import-preview'
      preLoaderRoute: typeof ImportPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigureRoute: ConfigureRoute,
  EditorRoute: EditorRoute,
  ImportRoute: ImportRoute,
  ImportPreviewRoute: ImportPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
