/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidateAddressesRouteImport } from './routes/validate-addresses'
import { Route as ImportPreviewRouteImport } from './routes/import-preview'
import { Route as ImportRouteImport } from './routes/import'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as IndexRouteImport } from './routes/index'

const ValidateAddressesRoute = ValidateAddressesRouteImport.update({
  id: '/validate-addresses',
  path: '/validate-addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportPreviewRoute = ImportPreviewRouteImport.update({
  id: '/import-preview',
  path: '/import-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/import': typeof ImportRoute
  '/import-preview': typeof ImportPreviewRoute
  '/validate-addresses': typeof ValidateAddressesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/import': typeof ImportRoute
  '/import-preview': typeof ImportPreviewRoute
  '/validate-addresses': typeof ValidateAddressesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/import': typeof ImportRoute
  '/import-preview': typeof ImportPreviewRoute
  '/validate-addresses': typeof ValidateAddressesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor'
    | '/import'
    | '/import-preview'
    | '/validate-addresses'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/import' | '/import-preview' | '/validate-addresses'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/import'
    | '/import-preview'
    | '/validate-addresses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  ImportRoute: typeof ImportRoute
  ImportPreviewRoute: typeof ImportPreviewRoute
  ValidateAddressesRoute: typeof ValidateAddressesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validate-addresses': {
      id: '/validate-addresses'
      path: '/validate-addresses'
      fullPath: '/validate-addresses'
      preLoaderRoute: typeof ValidateAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-preview': {
      id: '/import-preview'
      path: '/import-preview'
      fullPath: '/import-preview'
      preLoaderRoute: typeof ImportPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  ImportRoute: ImportRoute,
  ImportPreviewRoute: ImportPreviewRoute,
  ValidateAddressesRoute: ValidateAddressesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
